name:                gameverif
version:             0.1.0
github:              "ejconlon/gameverif"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2022 Eric Conlon"
# category:            Undefined
# synopsis:            Undefined

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/gameverif#readme>

dependencies:
- base >= 4.12 && < 5
- errata
- containers
- exceptions
- mtl
- prettyprinter
- recursion-schemes
- simple-parser
- text
- text-builder
- transformers
- unliftio-core

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

executables:
  gameverif-exe:
    main:                Main.hs
    source-dirs:         exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameverif

tests:
  gameverif-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameverif
    - tasty
    - tasty-hunit
